package org.easybooks.bookstore.vo;
// Generated 2020年10月30日 下午3:55:50 by Hibernate Tools 5.4.21.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Catalog generated by hbm2java
 */
public class Catalog implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer catalogId;
	private String catalogName;
	private Set<?> books = new HashSet<Object>(0);

	public Catalog() {
	}

	public Catalog(String catalogName) {
		this.catalogName = catalogName;
	}

	public Catalog(String catalogName, Set<?> books) {
		this.catalogName = catalogName;
		this.books = books;
	}

	public Integer getCatalogId() {
		return this.catalogId;
	}

	public void setCatalogId(Integer catalogId) {
		this.catalogId = catalogId;
	}

	public String getCatalogName() {
		return this.catalogName;
	}

	public void setCatalogName(String catalogName) {
		this.catalogName = catalogName;
	}

	public Set<?> getBooks() {
		return this.books;
	}

	public void setBooks(Set<?> books) {
		this.books = books;
	}

}
