package org.easybooks.bookstore.vo;
// Generated 2020年10月30日 下午3:55:50 by Hibernate Tools 5.4.21.Final

/**
 * OrderItem generated by hbm2java
 */
public class OrderItem implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer orderItemId;
	private Book book;
	private Order order;
	private int quantity;

	public OrderItem() {
	}

	public OrderItem(Book book, Order order, int quantity) {
		this.book = book;
		this.order = order;
		this.quantity = quantity;
	}

	public OrderItem(Book book, int quantity) {
		// TODO Auto-generated constructor stub
		this.book = book;
		this.quantity = quantity;
	}

	public Integer getOrderItemId() {
		return this.orderItemId;
	}

	public void setOrderItemId(Integer orderItemId) {
		this.orderItemId = orderItemId;
	}

	public Book getBook() {
		return this.book;
	}

	public void setBook(Book book) {
		this.book = book;
	}

	public Order getOrder() {
		return this.order;
	}

	public void setOrder(Order order) {
		this.order = order;
	}

	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

}
