package org.easybooks.bookstore.vo;
// Generated 2020年10月30日 下午3:55:50 by Hibernate Tools 5.4.21.Final

import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer userId;
	private String userName;
	private String passWord;
	private String sex;
	private Integer age;
	private Set<?> orders = new HashSet<Object>(0);

	public User() {
	}

	public User(String userName, String passWord) {
		this.userName = userName;
		this.passWord = passWord;
	}

	public User(String userName, String passWord, String sex, Integer age, Set<?> orders) {
		this.userName = userName;
		this.passWord = passWord;
		this.sex = sex;
		this.age = age;
		this.orders = orders;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getPassWord() {
		return this.passWord;
	}

	public void setPassWord(String passWord) {
		this.passWord = passWord;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	public Set<?> getOrders() {
		return this.orders;
	}

	public void setOrders(Set<?> orders) {
		this.orders = orders;
	}

}
